actas/urls.py
from django.urls import path
from actas import views

urlpatterns = [
    path('', views.Inicio.as_view(), name="inicio"),
    path('subir/', views.CrearActa.as_view(), name="crear_acta"),
    path('borrar/<str:pk>/', views.BorrarActa, name="borrar_acta"),
    path('actualizar/<str:pk>/', views.UpdateActa.as_view(), name="update_acta"),
    path('enviar/', views.EnviarMail, name="enviar_mail"),
    path('foto/', views.SubirFoto.as_view(), name="subir_foto"),
    path('eliminar/<str:pk>/', views.BorrarFoto, name="borrar_foto"),
]

cabil/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('actas.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

actas/models.py
from django.db import models
import uuid
from django.utils.timezone import now
from taggit.managers import TaggableManager
from urllib.parse import urlparse

class Acta(models.Model):
    codigo = models.AutoField(primary_key=True)
    fecha_subida = models.DateTimeField(default=now)
    titulo = models.CharField(max_length=250)
    descripcion = models.TextField()
    archivo = models.FileField(upload_to='documentos/', help_text='Máximo 5MB', null=True, blank=True)
    link = models.URLField(blank=True)
    tags = TaggableManager(help_text="Separar tags con comas")

    @property
    def youtube(self):
        if self.link:
            hostname = urlparse(self.link).hostname
            if 'www.youtube.com' in hostname:
                codigo = urlparse(self.link).query.replace('v=', '')
                return f'https://www.youtube.com/embed/{codigo}'
            elif 'youtu.be' in hostname:
                codigo = urlparse(self.link).path.replace('/', '')
                return f'https://www.youtube.com/embed/{codigo}'
            else:
                return False
        return False

class Foto(models.Model):
    archivo = models.ImageField(upload_to='documentos/')
    descripcion = models.TextField(help_text="Descripción de lo que está ocurriendo en la imagen. Necesario para ser inclusivo con los estudiantes con visión limitada")

actas/forms.py
from django import forms
from actas.models import Acta, Foto
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _
from captcha.fields import ReCaptchaField

from actas.funciones import modificar_imagen

class ActaForm(forms.ModelForm):
    class Meta:
        model = Acta
        fields = ('titulo', 'descripcion', 'archivo', 'link', 'tags',)
        widgets = {
            'titulo': forms.TextInput(attrs={'class':'input'}),
            'link': forms.TextInput(attrs={'class':'input'}),
            'descripcion': forms.Textarea(attrs={'class':'textarea'}),
            'archivo': forms.ClearableFileInput(attrs={'class': 'file-input', 'accept': '.pdf, .doc, .docx, .odt, .xml, application/msword, application/pdf, application/vnd.oasis.opendocument.text, application/vnd.openxmlformats-officedocument.wordprocessingml.document'}),
        }
    
    def clean(self):
        super(ActaForm, self).clean()
        link = self.cleaned_data.get('link')
        archivo = self.cleaned_data.get('archivo')
        if link and archivo:
            raise ValidationError(_('Puedes subir o un archivo o un enlance, no ambos'))
        if not link and not archivo:
            raise ValidationError(_('Debes subir al menos un tipo de recurso: o un archivo o un enlance'))

    def clean_archivo(self):
        data = self.cleaned_data['archivo']
        if data:
            if data.size > 5242880:
                raise ValidationError(_('El archivo no debe pesar más de 5 MB'))
        return data

class MailArchivo(forms.Form):
    nombre = forms.CharField(required=True, 
                             min_length=5, 
                             max_length=100,
                             widget=forms.TextInput(attrs={'class': 'input'}))

    correo = forms.EmailField(required=True,
                              widget=forms.EmailInput(attrs={'class': 'input'})) 

    descripcion = forms.CharField(required=True,
                                  max_length=500,
                                 label="Mensaje",
                                 widget=forms.Textarea(attrs={'class': 'textarea'}))

    archivo = forms.FileField(required=True,
                              help_text='El archivo no debe superar los 5 MB',
                              widget=forms.ClearableFileInput(attrs={'class': 'file-input', 'accept': '.pdf, .doc, .docx, .odt, .xml, application/msword, application/pdf, application/vnd.oasis.opendocument.text, application/vnd.openxmlformats-officedocument.wordprocessingml.document'}))

    captcha = ReCaptchaField()

    def clean_archivo(self):
        data = self.cleaned_data['archivo']
        if data.size > 5242880:
            raise ValidationError(_('El archivo no debe pesar más de 5 MB'))
        return data

class FotoForm(forms.ModelForm):
    class Meta:
        model = Foto
        fields = ('archivo', 'descripcion')
        widgets = {
            'descripcion': forms.Textarea(attrs={'class':'textarea'}),
            'archivo': forms.ClearableFileInput(attrs={'class': 'file-input', 'accept': 'image/*'}),
        }

    def clean_archivo(self):
        data = self.cleaned_data['archivo']
        imgfile = modificar_imagen(data)
        return imgfile

actas/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import ListView
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.views.decorators.http import require_POST
from django.urls import reverse_lazy, reverse
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from taggit.models import Tag
from django.http import HttpResponseRedirect
from django.core.mail import EmailMessage, BadHeaderError

from actas.models import Acta, Foto
from actas.forms import ActaForm, MailArchivo, FotoForm
from actas.funciones import pedazos

from cabil.settings import DEFAULT_FROM_EMAIL

class Inicio(ListView):
    model = Acta
    context_object_name = 'documentos'
    template_name= 'index.html'

    def get_context_data(self, **kwargs):
        context = super(Inicio, self).get_context_data(**kwargs)
        context['tags'] = Acta.tags.all()
        context['fotos'] = list(pedazos(Foto.objects.all(), 3))
        return context

class SubirFoto(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Foto
    template_name = 'subir_foto.html'
    form_class = FotoForm
    success_url = reverse_lazy('inicio')
    success_message = 'La fotografía ha sido publicada exitosamente'

class CrearActa(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Acta
    template_name = 'crear_acta.html'
    form_class = ActaForm
    success_url = reverse_lazy('inicio')
    success_message = 'El documento "%(titulo)s" ha sido publicado con éxito'

    def get_context_data(self, **kwargs):
        context = super(CrearActa, self).get_context_data(**kwargs)
        context['tags'] = Acta.tags.all()
        return context

class UpdateActa(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Acta
    form_class = ActaForm
    template_name = 'update_acta.html'
    success_url = reverse_lazy('inicio')
    success_message = 'El documento %(titulo)s fue actualizado con éxito'

@require_POST
def BorrarActa(request, pk):
    query = Acta.objects.get(pk=pk)
    query.archivo.delete(save=False)
    query.delete()
    messages.success(request, f'Has eliminado el documento {query.titulo}')
    return redirect('inicio')

@require_POST
def BorrarFoto(request, pk):
    query = Foto.objects.get(pk=pk)
    query.archivo.delete(save=False)
    query.delete()
    messages.success(request, f'Has eliminado una fotografía exitosamente')
    return redirect('inicio')

def EnviarMail(request):
    if request.method == 'POST':
        form = MailArchivo(request.POST, request.FILES)
        if form.is_valid():
            correo = form.cleaned_data['correo']
            nombre = form.cleaned_data['nombre']
            descripcion = form.cleaned_data['descripcion']
            archivo = form.cleaned_data['archivo']
            try:
                msg = EmailMessage(
                    subject=f'Correo de {nombre} <{correo}>',
                    body = descripcion,
                    from_email = DEFAULT_FROM_EMAIL,
                    to = [DEFAULT_FROM_EMAIL,],
                    reply_to=[correo,],
                )
                msg.attach(archivo.name, archivo.read(), archivo.content_type)
                msg.send()
            except BadHeaderError:
                messages.error(request, f'Hubo un error durante el envío del correo')
                return HttpResponseRedirect(reverse('inicio'))
            messages.success(request, f'El correo se ha enviado exitosamente')
            return HttpResponseRedirect(reverse('inicio'))
    else:
        form = MailArchivo()

    return render(request, 'correo_archivo.html', {'form': form})

actas/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes">
	<meta name="description" content="Diálogos es una serie de instancias de discusión y acción promovidas por la Facultad">
	{% load static %}
	<title>{% block title%}Diálogos{% endblock %}</title>
	<link rel="stylesheet" href="{% static 'faif.css' %}">
	<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

	<!--[if lt IE 9]>
	<script src="{% static 'html5shiv.min.js' %}"></script>
        <![endif]-->

	{% block css %}{% endblock %}

</head>
<body>

<!--

	Sitio web creado por Daniel Corvalán
	https://corvalan.dev

	¡CHÚPALO KAROL DANCE!

-->

	<div class="container">

<!-- INICIO DE LA NAVBAR -->

<nav class="navbar" aria-label="main navigation">
  <div class="navbar-brand">
	  <a class="navbar-item" href="{% url 'inicio' %}">
		  <img src="{% static 'logo.png' %}" width="112" height="28" alt="Logo de Diálogos"
>
	  </a>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
	    <a class="navbar-item {% block activo_inicio %}{% endblock %}" href="{% url 'inicio' %}">
        Inicio
      </a>

      <a class="navbar-item {% block activo_enviar %}{% endblock %}" href="{% url 'enviar_mail' %}">
	Enviar documento
      </a>

      {% if user.is_authenticated %}
      <a class="navbar-item {% block activo_subir %}{% endblock %}" href="{% url 'crear_acta' %}">
        Subir recurso
      </a>

      <a class="navbar-item {% block activo_foto %}{% endblock %}" href="{% url 'subir_foto' %}">
        Subir foto
      </a>
      {% endif %}

    </div>

    <div class="navbar-end">
      <div class="navbar-item {% block activo_login %}{% endblock %}">
        <div class="buttons">
	  {% if user.is_authenticated %}
      	  <div class="navbar-item">
		  <p>Hola, {{ user.get_short_name }}</p>
          </div>
	  <div class="navbar-item">
	  <a class="button is-light" href="{% url 'logout' %}?next=/">
            Logout
          </a>
	  </div>
	  {% else %}
	  <div class="navbar-item">
	  <a class="button is-light" href="{% url 'login' %}">
            Log in
	  </a>
          </div>
	  {% endif %}
        </div>
      </div>
    </div>
  </div>
</nav>

{% block content %}{% endblock %}

<!-- INICIO DEL FOOTER -->
<footer class="footer">
  <div class="content has-text-centered has-text-white">
	  <p>
	  2019 © Diálogos {{ request.headers.user_agent }}<br>
	  Teléfonos: <a style="color:inherit;" href="tel:+5622222222">(56 2) 222 2222</a><br>
	  <a style="color:inherit;" href="{% if 'iPhone' in request.META.HTTP_USER_AGENT or 'iPad' in request.META.HTTP_USER_AGENT %}maps://?q={% elif 'Android' in request.META.HTTP_USER_AGENT %}geo://?q={% else %}https://www.google.com/maps/search/?api=1&query={% endif %}Melipilla%2C+Chile">Melipilla, Chile</a>
	  </p>
	  <a aria-label="Presiona para acceder a nuestra cuenta en Twitter" href="https://twitter.com/coderdojomeli">
		  <span class="card-icon is-large">
			  <i class="fab fa-lg fa-twitter-square" aria-hidden="true"></i>
		  </span>
	  </a>
	  <a aria-label="Presiona para acceder a nuestro fanpage en Facebook" href="https://www.facebook.com/coderdojomeli/">
		  <span class="card-icon is-large">
			  <i class="fab fa-lg fa-facebook-square" aria-hidden="true"></i>
		  </span>
	  </a>
	  <a aria-label="Presiona para acceder a nuestra cuenta en Instagram" href="https://www.instagram.com/coderdojomeli/">
		  <span class="card-icon is-large">
			  <i class="fab fa-lg fa-instagram" aria-hidden="true"></i>
		  </span>
	  </a>

  </div>
</footer>

{% block javascript %}{% endblock %}
<script>
// DROPDOWN NAV
document.addEventListener('DOMContentLoaded', function(){

  // Get all "navbar-burger" elements
  const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

  // Check if there are any navbar burgers
  if ($navbarBurgers.length > 0) {

    // Add a click event on each of them
    $navbarBurgers.forEach( function(el) {
      el.addEventListener('click', function() {

        // Get the target from the "data-target" attribute
        const target = el.dataset.target;
        const $target = document.getElementById(target);

        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
        el.classList.toggle('is-active');
        $target.classList.toggle('is-active');

      });
    });
  }

});
</script>

</div>
</body>
</html>

actas/templates/correo_archivo.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Enviar documento - Diálogos {% endblock %}

{% block activo_enviar %}is-active{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'form.css' %}">
{% endblock%}

{% block content %}
<div class="section">
<div class="box has-text-centered">
	<strong>Si tuvieras algún problema enviando el archivo por este medio, puedes enviarlo a contacto@noexiste.com</strong>
</div>
<form action="" method="post" enctype="multipart/form-data" id="nueva_acta">
	{% csrf_token %}
	
{% for error in form.non_field_errors %}
<article class="message is-warning">
        <div class="message-header is-warning">
                {{ error }}
                <button type="button" class="delete" data-dismiss="alert" aria-label="delete">
                        <span aria-hidden="true">&times;</span>
                </button>
        </div>
</article>
{% endfor %}

	{% for field in form  %}
		{% if field.html_name == 'archivo' %}
<div>{{ field.errors }}</div>
<div id="documento" class="field file has-name">
	<label class="file-label" for="{{ field.id_for_label }}">
		{{ field }}
    <span class="file-cta">
      <span class="file-icon">
        <i class="fas fa-upload"></i>
      </span>
      <span class="file-label">
        Selecciona un archivo…
      </span>
    </span>
    <span class="file-name">
	    Sin archivo
    </span>
  </label>
</div>
<p class="help-text">{{ field.help_text }}</p>

		{% else %}
	<div class="field">
		<label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
		{{ field.errors }}
		{{ field }}
		{{ field.help_text }}
	</div>
		{% endif %}
	{% endfor %}

	<div class="field is-grouped ">
		<div class="control">
			<button class="button is-link">Enviar</button>
		</div>
		<div class="control">
			<a class="button is-link is-light" href="{% url 'inicio' %}">Cancelar</a>
		</div>
	</div>
</form>
</div>

{% endblock %}

{% block javascript %}
<script src="{% static 'comun.js' %}"></script>
{% endblock %}

actas/templates/crear_acta.html
{% extends 'base.html' %}
{% load static %}
{% load actastag %}

{% block title %}Subir documento - Diálogos {% endblock %}

{% block activo_subir %}is-active{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'form.css' %}">
{% endblock%}

{% block content %}
<div class="section">
<form action="" method="post" enctype="multipart/form-data" id="nueva_acta">
	{% csrf_token %}

{% for error in form.non_field_errors %}
<article class="message is-warning">
        <div class="message-header is-warning">
		{{ error }}
                <button type="button" class="delete" data-dismiss="alert" aria-label="delete">
                        <span aria-hidden="true">&times;</span>
                </button>
        </div>
</article>
{% endfor %}

	{% for field in form  %}
		{% if field.html_name == 'archivo' %}
<div>{{ field.errors }}</div>
<div id="documento" class="field file has-name">
	<label class="file-label" for="{{ field.id_for_label }}">
		{{ field }}
    <span class="file-cta">
      <span class="file-icon">
        <i class="fas fa-upload"></i>
      </span>
      <span class="file-label">
        Selecciona un archivo…
      </span>
    </span>
    <span class="file-name">
	    {{ field.value|default_if_none:"Sin archivo"}}
    </span>
  </label>
    	{% if field.value %}
                <button type="button" class="delete" id="delete_doc" data-dismiss="alert" aria-label="delete">
                        <span aria-hidden="true">&times;</span>
                </button>
	{% endif %}
</div>
<p class="help-text">{{ field.help_text }}</p>
		{% elif field.html_name == 'tags' %}
	<div class="field">
		<label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
		{{ field.errors }}
		<input id="id_tags" class="input" type="text" name="tags" list="availabletags" autocomplete="off" value="{{ field.value|get_tags|default_if_none:"" }}" required>
		{{ field.help_text }}
	</div>
	<datalist id="availabletags">
		{% for tag in tags %}
		<option value="{{ tag }}">
		{% endfor %}
	</datalist>
		{% else %}
	<div class="field">
		<label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
		{{ field.errors }}
		{{ field }}
	</div>
		{% endif %}
	{% endfor %}

	<div class="field is-grouped ">
		<div class="control">
			<button class="button is-link">Subir</button>
		</div>
		<div class="control">
			<a class="button is-link is-light" href="{% url 'inicio' %}">Cancelar</a>
		</div>
	</div>
</form>
</div>
{% endblock %}

{% block javascript %}
<script src="{% static 'comun.js' %}"></script>
{% endblock %}

actas/templates/subir_foto.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Subir foto - Diálogos {% endblock %}

{% block activo_foto %}is-active{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'form.css' %}">
{% endblock%}

{% block content %}
<div class="section">
<form action="" method="post" enctype="multipart/form-data" id="nueva_foto">
	{% csrf_token %}

{% for error in form.non_field_errors %}
<article class="message is-warning">
        <div class="message-header is-warning">
		{{ error }}
                <button type="button" class="delete" data-dismiss="alert" aria-label="delete">
                        <span aria-hidden="true">&times;</span>
                </button>
        </div>
</article>
{% endfor %}

	{% for field in form  %}
		{% if field.html_name == 'archivo' %}
<div>{{ field.errors }}</div>
<label class="label">Foto</label>
<div id="documento" class="field file has-name">
	<label class="file-label" for="{{ field.id_for_label }}">
		{{ field }}
    <span class="file-cta">
      <span class="file-icon">
        <i class="fas fa-upload"></i>
      </span>
      <span class="file-label">
        Selecciona un archivo…
      </span>
    </span>
    <span class="file-name">
	    {{ field.value|default_if_none:"Sin archivo"}}
    </span>
  </label>
    	{% if field.value %}
                <button type="button" class="delete" id="delete_doc" data-dismiss="alert" aria-label="delete">
                        <span aria-hidden="true">&times;</span>
                </button>
	{% endif %}
  <p class="help-text">{{ field.help_text }}</p>
</div>

		{% else %}
	<div class="field">
		<label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
		{{ field.errors }}
		{{ field }}
		{{ field.help_text }}
	</div>
		{% endif %}
	{% endfor %}

	<div class="field is-grouped ">
		<div class="control">
			<button class="button is-link">Subir</button>
		</div>
		<div class="control">
			<a class="button is-link is-light" href="{% url 'inicio' %}">Cancelar</a>
		</div>
	</div>
</form>
</div>
{% endblock %}

{% block javascript %}
<script src="{% static 'comun.js' %}"></script>
{% endblock %}

actas/templates/update_acta.html
{% extends 'base.html' %}
{% load static %}
{% load actastag %}

{% block title %}Actualizar documento - Diálogos {% endblock %}

{% block activo_subir %}is-active{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'form.css' %}">
{% endblock%}

{% block content %}
<div class="section">
<form action="" method="post" enctype="multipart/form-data" id="nueva_acta">
	{% csrf_token %}

{% for error in form.non_field_errors %}
<article class="message is-warning">
        <div class="message-header is-warning">
                {{ error }}
                <button type="button" class="delete" data-dismiss="alert" aria-label="delete">
                        <span aria-hidden="true">&times;</span>
                </button>
        </div>
</article>
{% endfor %}

	{% for field in form  %}
		{% if field.html_name == 'archivo' %}
<div>{{ field.errors}}</div>
<div id="documento" class="field file has-name">
	<label class="file-label" for="{{ field.id_for_label }}">
	<input type="file" class="file-input" id="id_archivo" name="archivo" accept=".pdf, .doc, .docx, .odt, .xml, application/msword, application/pdf, application/vnd.oasis.opendocument.text, application/vnd.openxmlformats-officedocument.wordprocessingml.document">
    <span class="file-cta">
      <span class="file-icon">
        <i class="fas fa-upload"></i>
      </span>
      <span class="file-label">
        Selecciona un archivo…
      </span>
    </span>
    <span class="file-name">
	    {{ field.value|default:"Sin archivo" }}
    </span>
  </label>
          {% if field.value %}
                <button type="button" class="delete" id="delete_doc" data-dismiss="alert" aria-label="delete">
                        <span aria-hidden="true">&times;</span>
                </button>
        {% endif %}
</div>
<p class="help-text">{{ field.help_text }}<p>
		{% elif field.html_name == 'tags' %}
        <div class="field">
                <label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
                {{ field.errors }}
		<input id="id_tags" class="input" type="text" name="tags" list="availabletags" value="{{ field.value|get_tags }}" autocomplete="off" required>
		{{ field.help_text }}
        </div>
        <datalist id="availabletags">
                {% for tag in tags %}
                <option value="{{ tag }}">
                {% endfor %}
        </datalist>

		{% else %}
	<div class="field">
		<label for="{{ field.id_for_label }}" class="label">{{ field.label }}</label>
		{{ field.errors }}
		{{ field }}
	</div>
		{% endif %}
	{% endfor %}

	<div class="field is-grouped ">
		<div class="control">
			<button class="button is-link">Actualizar</button>
		</div>
		<div class="control">
			<a class="button" href="{% url 'inicio' %}" class="button is-link is-light">Cancelar</a>
		</div>
	</div>
</form>
</div>

{% endblock %}

{% block javascript %}
<script src="{% static 'comun.js' %}"></script>
{% endblock %}